### ISSUE TITLE
Include TWDTW classification in sits

### ISSUE THREAD

**Issue by gilbertocamara** [e-sensing/sits#1021]
**Describe the new API function requested**
Include the new version of the `dtwSat` package by @vwmaus in `sits`. The previous version of `dtwSat` used the S4 model, which made it difficult to integrate the algorithm in `sits`. The new version uses S3, thus making the integration of `dtwSat` into `sits`. 

**Associated sits API function**
Develop a new `sits_dtw()` that can be used in connection with `sits_train()`.

**Comment by vwmaus** [comment]
**Implementation steps:**
- [ ] Build a test set
- [ ] Create a new method in `dtwSat` that supports inputs from `sits` and returns a `twdtw_knn1` model
- [ ] Integrate the `twdtw_knn1` to `sits_twdtw()`

**Comment by OldLipe** [comment]
Move this issue to #1099.
